name: flutter_app
description: Realtime messenger client for go-flutter-messenger.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  mime: ^1.0.5
  web_socket_channel: ^3.0.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
